# Generated by Django 5.2.5 on 2025-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('MEXICAN', 'Mexican'), ('FRENCH', 'French'), ('BRAZIL', 'Brazilian'), ('ITALIAN', 'Italian'), ('GERMAN', 'German'), ('BRITISH', 'British'), ('CANADIAN', 'Canadian'), ('AUSTRALIAN', 'Australian'), ('OTHER', 'Other')], max_length=100, null=True)),
            ],
        ),
    ]
